// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

//包名，通过protoc生成时go文件时

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登录请求
type UserLoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//登录返回
type UserLoginResp struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	TalkId               uint64   `protobuf:"varint,2,opt,name=talk_id,json=talkId,proto3" json:"talk_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Zone                 string   `protobuf:"bytes,7,opt,name=zone,proto3" json:"zone,omitempty"`
	Mobile               string   `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResp) Reset()         { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()    {}
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResp.Unmarshal(m, b)
}
func (m *UserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResp.Marshal(b, m, deterministic)
}
func (m *UserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResp.Merge(m, src)
}
func (m *UserLoginResp) XXX_Size() int {
	return xxx_messageInfo_UserLoginResp.Size(m)
}
func (m *UserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResp proto.InternalMessageInfo

func (m *UserLoginResp) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *UserLoginResp) GetTalkId() uint64 {
	if m != nil {
		return m.TalkId
	}
	return 0
}

func (m *UserLoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserLoginResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginResp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserLoginResp) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserLoginResp) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *UserLoginResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type RegisterReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterReq) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *RegisterReq) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *RegisterReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*UserLoginReq)(nil), "user.UserLoginReq")
	proto.RegisterType((*UserLoginResp)(nil), "user.UserLoginResp")
	proto.RegisterType((*RegisterReq)(nil), "user.RegisterReq")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0x37, 0x9b, 0xd6, 0x51, 0x41, 0x82, 0x68, 0xf0, 0x54, 0xf6, 0xd4, 0x93, 0x17,
	0xdf, 0x41, 0x28, 0x78, 0x0a, 0x78, 0x96, 0xad, 0x3b, 0x94, 0xb0, 0x6d, 0x66, 0x4d, 0x22, 0x8a,
	0x2f, 0xe3, 0x13, 0xf9, 0x4e, 0x32, 0x89, 0x2d, 0x5d, 0xda, 0x83, 0xb7, 0xf9, 0xf2, 0x0f, 0xc3,
	0xc7, 0x1f, 0x80, 0xf7, 0x88, 0xe1, 0x7e, 0x08, 0x94, 0x48, 0x4b, 0x9e, 0x9b, 0x47, 0xb8, 0x78,
	0x8e, 0x18, 0x9e, 0x68, 0xed, 0xbc, 0xc5, 0x37, 0x7d, 0x07, 0x33, 0x7e, 0xf7, 0xed, 0x16, 0x8d,
	0x98, 0x8b, 0xc5, 0x99, 0xdd, 0x33, 0x67, 0x43, 0x1b, 0xe3, 0x07, 0x85, 0xce, 0x4c, 0x4a, 0xb6,
	0xe3, 0xe6, 0x47, 0xc0, 0xe5, 0xc1, 0xa1, 0x38, 0xe8, 0x5b, 0x98, 0xd2, 0x80, 0xfe, 0xc5, 0x75,
	0x7f, 0x87, 0x14, 0xe3, 0xb2, 0xe3, 0x20, 0xb5, 0x9b, 0x9e, 0x03, 0xbe, 0x22, 0xad, 0x62, 0x5c,
	0x76, 0xfa, 0x1a, 0xea, 0x44, 0x3d, 0x7a, 0x53, 0xe5, 0xfd, 0x02, 0x23, 0x23, 0x79, 0x6c, 0xe4,
	0xdd, 0x6b, 0x9f, 0xb3, 0xba, 0x64, 0x3b, 0xd6, 0x57, 0x50, 0x45, 0xfc, 0x34, 0x6a, 0x2e, 0x16,
	0xb5, 0xe5, 0x51, 0x6b, 0x90, 0x5f, 0xe4, 0xd1, 0x4c, 0xf3, 0x66, 0x9e, 0xf5, 0x0d, 0xa8, 0x2d,
	0xad, 0xdc, 0x06, 0xcd, 0xac, 0x48, 0x16, 0x6a, 0xbe, 0x05, 0x9c, 0x5b, 0x5c, 0xbb, 0x98, 0x30,
	0xfc, 0xa3, 0x97, 0xbd, 0xc5, 0xe4, 0xb4, 0x45, 0x75, 0x6c, 0x21, 0x4f, 0x5a, 0xd4, 0x87, 0x16,
	0xa3, 0xc6, 0xd5, 0xb8, 0xf1, 0x95, 0xca, 0xdf, 0xf8, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xb6,
	0x3d, 0x4d, 0x5c, 0xd4, 0x01, 0x00, 0x00,
}
