// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

//包名，通过protoc生成时go文件时

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserVo struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	TalkId               uint64   `protobuf:"varint,2,opt,name=talk_id,json=talkId,proto3" json:"talk_id,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVo) Reset()         { *m = UserVo{} }
func (m *UserVo) String() string { return proto.CompactTextString(m) }
func (*UserVo) ProtoMessage()    {}
func (*UserVo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserVo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVo.Unmarshal(m, b)
}
func (m *UserVo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVo.Marshal(b, m, deterministic)
}
func (m *UserVo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVo.Merge(m, src)
}
func (m *UserVo) XXX_Size() int {
	return xxx_messageInfo_UserVo.Size(m)
}
func (m *UserVo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVo.DiscardUnknown(m)
}

var xxx_messageInfo_UserVo proto.InternalMessageInfo

func (m *UserVo) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *UserVo) GetTalkId() uint64 {
	if m != nil {
		return m.TalkId
	}
	return 0
}

func (m *UserVo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserVo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

//登录请求
type UserLoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//登录返回
type UserLoginResp struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	TalkId               uint64   `protobuf:"varint,2,opt,name=talk_id,json=talkId,proto3" json:"talk_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Zone                 string   `protobuf:"bytes,7,opt,name=zone,proto3" json:"zone,omitempty"`
	Mobile               string   `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResp) Reset()         { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()    {}
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResp.Unmarshal(m, b)
}
func (m *UserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResp.Marshal(b, m, deterministic)
}
func (m *UserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResp.Merge(m, src)
}
func (m *UserLoginResp) XXX_Size() int {
	return xxx_messageInfo_UserLoginResp.Size(m)
}
func (m *UserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResp proto.InternalMessageInfo

func (m *UserLoginResp) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *UserLoginResp) GetTalkId() uint64 {
	if m != nil {
		return m.TalkId
	}
	return 0
}

func (m *UserLoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserLoginResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginResp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserLoginResp) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserLoginResp) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *UserLoginResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

// 注册请求
type RegisterReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterReq) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *RegisterReq) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *RegisterReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 查询单个用户的请求
type UserQueryReq struct {
	TalkId               uint64   `protobuf:"varint,1,opt,name=talk_id,json=talkId,proto3" json:"talk_id,omitempty"`
	OpenId               string   `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserQueryReq) Reset()         { *m = UserQueryReq{} }
func (m *UserQueryReq) String() string { return proto.CompactTextString(m) }
func (*UserQueryReq) ProtoMessage()    {}
func (*UserQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserQueryReq.Unmarshal(m, b)
}
func (m *UserQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserQueryReq.Marshal(b, m, deterministic)
}
func (m *UserQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserQueryReq.Merge(m, src)
}
func (m *UserQueryReq) XXX_Size() int {
	return xxx_messageInfo_UserQueryReq.Size(m)
}
func (m *UserQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserQueryReq proto.InternalMessageInfo

func (m *UserQueryReq) GetTalkId() uint64 {
	if m != nil {
		return m.TalkId
	}
	return 0
}

func (m *UserQueryReq) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *UserQueryReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func init() {
	proto.RegisterType((*UserVo)(nil), "user.UserVo")
	proto.RegisterType((*UserLoginReq)(nil), "user.UserLoginReq")
	proto.RegisterType((*UserLoginResp)(nil), "user.UserLoginResp")
	proto.RegisterType((*RegisterReq)(nil), "user.RegisterReq")
	proto.RegisterType((*UserQueryReq)(nil), "user.UserQueryReq")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x49, 0x9b, 0x66, 0x77, 0x47, 0x05, 0x09, 0xa2, 0xc5, 0x53, 0xe9, 0xa9, 0x27, 0x2f,
	0xbe, 0x83, 0xb0, 0xe0, 0xc5, 0x80, 0xe2, 0x4d, 0xba, 0x76, 0x58, 0x4b, 0x77, 0x93, 0x9a, 0x74,
	0xf1, 0xcf, 0xcb, 0xf8, 0x44, 0xbe, 0x93, 0x4c, 0x23, 0xb1, 0x75, 0x7b, 0x10, 0x6f, 0xf3, 0x31,
	0x9d, 0x7e, 0xbf, 0xf9, 0x26, 0x00, 0x3b, 0x87, 0xf6, 0xa2, 0xb5, 0xa6, 0x33, 0x92, 0x53, 0x9d,
	0x3f, 0x81, 0xb8, 0x75, 0x68, 0xef, 0x8c, 0x3c, 0x83, 0x99, 0x69, 0x51, 0x3f, 0xd4, 0x55, 0xca,
	0x32, 0x56, 0x2c, 0x94, 0x20, 0xb9, 0xac, 0xa8, 0xd1, 0x95, 0x9b, 0x86, 0x1a, 0x51, 0xc6, 0x0a,
	0xae, 0x04, 0xc9, 0x65, 0x25, 0xcf, 0x61, 0xae, 0xeb, 0xc7, 0x46, 0x97, 0x5b, 0x4c, 0xe3, 0x7e,
	0x24, 0x68, 0x79, 0x0c, 0xb1, 0xc3, 0xd7, 0x94, 0x67, 0xac, 0x48, 0x14, 0x95, 0xf9, 0x15, 0x1c,
	0x92, 0xd3, 0xb5, 0x59, 0xd7, 0x5a, 0xe1, 0x33, 0x4d, 0x13, 0x41, 0x3f, 0xed, 0x0d, 0x83, 0xa6,
	0x5e, 0x5b, 0x3a, 0xf7, 0x62, 0xac, 0xf7, 0x5c, 0xa8, 0xa0, 0xf3, 0x4f, 0x06, 0x47, 0x83, 0x1f,
	0xb9, 0xf6, 0x1f, 0xe4, 0x27, 0x90, 0x74, 0xa6, 0x41, 0xfd, 0x8d, 0xed, 0xc5, 0x88, 0x88, 0xef,
	0x13, 0x85, 0x5d, 0x93, 0xe9, 0x5d, 0x45, 0xd8, 0x55, 0x4a, 0xe0, 0xef, 0x46, 0x63, 0x3a, 0xeb,
	0xbf, 0xec, 0x6b, 0x79, 0x0a, 0x62, 0x6b, 0x56, 0xf5, 0x06, 0xd3, 0xb9, 0x87, 0xf4, 0x2a, 0xff,
	0x60, 0x70, 0xa0, 0x70, 0x5d, 0xbb, 0x0e, 0xed, 0x1f, 0x72, 0x09, 0x14, 0xd1, 0x34, 0x45, 0xbc,
	0x4f, 0xc1, 0x27, 0x29, 0x92, 0x21, 0xc5, 0x28, 0x71, 0xf1, 0x2b, 0xf1, 0x7b, 0x7f, 0xb9, 0x9b,
	0x1d, 0xda, 0x37, 0x22, 0x1c, 0xc4, 0xca, 0x46, 0xb1, 0x0e, 0x0e, 0x11, 0x8d, 0x0e, 0xf1, 0xe3,
	0x1a, 0x0f, 0x5d, 0x57, 0xa2, 0x7f, 0x8a, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x91, 0xbe,
	0x38, 0x96, 0x98, 0x02, 0x00, 0x00,
}
